export const gifFiles = [
    [0, 'ByuN_GG.gif'],
    [1, 'noGG_Parting.gif'],
    [2, 'highground.gif'],
    [3, 'coffin_dance.gif'],
    [4, 'transparent_greenscreen.gif'],
    [26, 'paula_white_victory.gif'],
    [6, 'rocky.gif'],
    [7, 'braveheart.gif'],
  ];

export const randomAudioFiles = [
    "production_files/audio/FSL_intro_2024_clip1.mp3",
    "production_files/audio/FSL_intro_2024_clip2.mp3",
    "production_files/audio/FSL_intro_2024_clip3.mp3",
    "production_files/audio/FSL_intro_2024_clip4.mp3",
    "production_files/audio/FSL_intro_2024_clip5.mp3",
    "production_files/audio/FSL_intro_2024_clip6.mp3",                    
    "production_files/audio/FSL_intro_2026_1.mp3",
    "production_files/audio/FSL_intro_2026_2.mp3",
    "production_files/audio/FSL_intro_2026_3.mp3",
    "production_files/audio/FSL_intro_2026_4.mp3",
    "production_files/audio/FSL_intro_2026_5.mp3",
    "production_files/audio/FSL_intro_2026_6.mp3",
    "production_files/audio/FSL_intro_2026_7.mp3",
    "production_files/audio/FSL_intro_2026_8.mp3",
    "production_files/audio/FSL_intro_2026_9.mp3",
    "production_files/audio/FSL_intro_2026_10.mp3",
    "production_files/audio/FSL_intro_2026_11.mp3",
    "production_files/audio/FSL_intro_2026_12.mp3",
    "production_files/audio/FSL_intro_2026_13.mp3",
    "production_files/audio/FSL_intro_2026_14.mp3",
    "production_files/audio/FSL_intro_2026_15.mp3",
    "production_files/audio/PSL_s2_intro.mp3",
    "production_files/audio/PSL_s2_intro2.mp3",
    "production_files/audio/PSL_s2_intro3.mp3",
    "production_files/audio/PSL_s2_intro4.mp3",
    "production_files/audio/PSL_s2_intro5.mp3",
    "production_files/audio/PSL_s2_intro6.mp3"    
];